spring:
#  profiles:
#    active: teste
  application:
    name: Ghast Consultory

  # Settando a base com o banco
  datasource:
    url: jdbc:postgresql://autorack.proxy.rlwy.net:29638/railway
    username: postgres
    password: xIAuEddbfSCJMaNFFSGznfuxRSonQhtP
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update # Criação automática de tabelas
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

