spring:
  application:
    name: Ghast Consultory

  # Settando a base com o banco
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: developer
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update # Criação automática de tabelas
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

